# AutoApiS 多功能版
name: Auto EEE Five

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: '0 1,5,8 * * 1-5'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup Python Environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.15
    - name: Install Dependencies
      run: |
        pip install requests
    - name: Load Secrets
      env: 
        SECRET_A: ${{ secrets.ID_LIST }} # secrets_id 提供
        SECRET_B: ${{ secrets.KEY_LIST }} # secrets_key 提供
        SECRET_C: ${{ secrets.ID_LIST2 }} # secrets_id 提供
        SECRET_D: ${{ secrets.KEY_LIST2 }} # secrets_key 提供
      run: | 
        echo $SECRET_A > temp_a.txt
        echo $SECRET_B > temp_b.txt
        sed -i '10 r temp_a.txt' testapi.py
        sed -i '11 r temp_b.txt' testapi.py
        echo $SECRET_C > temp_c.txt
        echo $SECRET_D > temp_d.txt
        sed -i '12 r temp_c.txt' testapi.py
        sed -i '13 r temp_d.txt' testapi.py
    - name: Execute Script
      run: | 
        python testapi.py
