name: random api

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: '18 18 * * *'
  watch:
    types: [started]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      A: AutoupdateRobot@email.com
      B: AutoupdateRobot
      C: 3.7.15
    steps:
    - name: step1
      uses: actions/checkout@master
    - name: step2
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.C }}
    - name: step3
      run: |
        python updaterand.py
    - name: step4
      run: |
        git config --global user.email ${{ env.A }}
        git config --global user.name ${{ env.B }}
    - name: step5
      run: |
        git add .
        git commit -m "commit"
    - name: step6
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
